# GitHub Action: 构建并推送到 GitHub Container Registry (GHCR)

name: Build and Push to GHCR (armv7)

# 触发器：当 'main' 分支有代码推送时，或手动触发时
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # 关键：授予 Action 写入 'Packages' (GHCR) 的权限
    permissions:
      contents: read
      packages: write # <-- 必须添加这行

    steps:
      # 1. 检出您的代码 (获取 Dockerfile)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 QEMU (用于模拟 armv7 环境)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. 设置 Docker Buildx (构建工具)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 登录到 GitHub Container Registry (GHCR)
      # 注意：这里不再需要 Docker Hub 密钥！
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # 'github.actor' 是您的 GitHub 用户名
          username: ${{ github.actor }} 
          # 'GITHUB_TOKEN' 是由 Action 自动生成的临时令牌
          password: ${{ secrets.GITHUB_TOKEN }} 

      # 5. 构建并推送镜像 (armv7)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v7 # 确保架构为 armv7
          push: true

          # 关键：修改镜像标签格式以匹配 GHCR
          # 它会自动使用 'ghcr.io/您的用户名/您的仓库名:latest'
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
